.TH FREENECT-GLPCVIEW 1 2012-05-21 OpenKinect "libfreenect manual"
.SH NAME
freenect-glpcview \- manual page for freenect camera test
.SH DESCRIPTION
.LP
This is a simple demo program that illustrates the use of the C synchronous
libfreenect library. It also provides a simple way to test the communication
with the freenect device.
.SS Shortcuts
.TP
.B ESC
Exit the program
.TP
.B Key W
Increase zoom
.TP
.B Key S
Decrease zoom
.TP
.B Key C
Switch on/off the texture image
.SH "SEE ALSO"
.BR fakenect (1),
.BR freenect-glview (1),
.BR freenect-cppview (1)
