.TH FREENECT-GLVIEW 1 2012-05-21 OpenKinect "libfreenect manual"
.SH NAME
freenect-glview \- manual page for freenect camera test
.SH SYNOPSIS
.SY freenect-glview 
.OP \fIdevice_index\fP
.SH DESCRIPTION
.LP
This is a simple demo program that illustrates the use of the libfreenect
library. It also provide a simple way to test the communication with the
freenect device.
.SS Shortcuts
.TP
.B ESC
Exit the program
.TP
.B Key W
Increase tilt
.TP
.B Key S
Reset tilt to 0
.TP
.B Key X
Decrease tilt
.TP
.B Key F
Change video format
.TP
.B Key 1
Change LED color to still green
.TP
.B Key 2
Change LED color to still red
.TP
.B Key 3
Change LED color to still yellow
.TP
.B Key 4
Change LED color to blinking green
.TP
.B Key 5
Change LED color to blinking green
.TP
.B Key 6
Change LED color to blinking red and yellow
.TP
.B Key 0
Switch off the LED
.SH OPTIONS
.TP 
.B \fIdevice_index\fP
Specify the index of device that should be used. This  option is useful when
several devices are connected.
.SH "SEE ALSO"
.BR fakenect (1),
.BR freenect-glpcview (1),
.BR freenect-cppview (1)
