.TH FREENECT-GLVIEW "1" "11 December 2010" "Freenect camera test" "User Commands"
.SH NAME
freenect-cppview \- manual page for freenect camera test
.SH SYNOPSYS
.B freenect-glview
.SH DESCRIPTION
This is a simple demo program from the OpenKinect project. To be able to use it, you need to connect a
kinect camera device to the USB port of your system. 
.PP
This program requires OpenGL (Glut) to be installed.
.PP
.SH "SEE ALSO"
The full documentation for
.B Freenect
is available in the libfreenect doc directory, 
see 
.B /usr/share/doc/libfreenect.
.SH AUTHORS
Arne Bernin (arne@alamut.de)

